### ISSUE TITLE
README still about MyST...

### ISSUE THREAD

**Issue by rkurchin** [Notebooks-Now/submission-quarto-full#1]
Looks like the README was copied from the MyST demo and not actually updated to reflect the Quarto things... 😉

If you like, I can make a PR just grabbing the one from the quarto-lite template, but I'm not sure if there's anything particular you'd want to add specific to this case...

**Comment by dragonstyle** [comment]
Thank you, I made some tweaks that get it close to the `lite` version with a few small diffs!
